services:
  eshopdb:
    image: postgres

 # distributedcache:
 #   image: redis
  
  eshop-seq:
    image: datalust/seq:latest

 # messagebus:
 #   image: rabbitmq:management

 # identity:
 #   image: quay.io/keycloak/keycloak:24.0.3

  eshop-api:
    image: ${DOCKER_REGISTRY-}api 
    build:
      context: .
      dockerfile: src/Bootstrapper/Api/Dockerfile

volumes:
  postgres_eshopdb: